Repository memOria-project/memOria, pull requests merged in 2021-11, with the labels that each got.

#58 Fixes #52 : enable card deletion even if delayed
  back/app/models/card.js
  back/migrations/deploy/deleteOnCascadeDelay.sql
  back/migrations/revert/deleteOnCascadeDelay.sql
  back/migrations/sqitch.plan
  back/migrations/verify/deleteOnCascadeDelay.sql
Labels: bug

#68 Refactor card display
  front/src/App.js
  front/src/components/CardDisplay/Next.js
  front/src/components/CardDisplay/NextGame.js
  front/src/components/CardDisplay/Options/DelayedCards.js
  front/src/components/CardDisplay/Options/RectoVerso.js
  front/src/components/CardDisplay/Options/index.js
  front/src/components/CardDisplay/Options/pickOrder.js
  front/src/components/CardDisplay/ShowCards.js
  front/src/components/CardDisplay/index.js
  front/src/components/CardDisplay/selectDatabase.js
  front/src/components/CardEditor/index.js
  front/src/components/Home/index.js
  front/src/components/NoMatch/setReason.js
  front/src/components/ResetCard/index.js
  front/src/middlewares/api.js
  front/src/reducers/currentDeck.js
  front/src/reducers/options.js
Labels: bug, Refactoring

#69 Deck order
  front/src/actions/index.js
  front/src/components/CardDisplay/CardDisplay_desktop.scss
  front/src/components/CardDisplay/Options/DeckOrder.js
  front/src/components/CardDisplay/Options/DelayedCards.js
  front/src/components/CardDisplay/Options/RectoVerso.js
  front/src/components/CardDisplay/Options/index.js
  front/src/components/CardDisplay/Options/pickOrder.js
  front/src/components/CardDisplay/Options/setClassName.js
  front/src/components/CardDisplay/ShowCards.js
  front/src/components/CardDisplay/index.js
  front/src/components/CardDisplay/selectDatabase.js
  front/src/components/Team/index.js
  front/src/reducers/options.js
Labels: bug, enhancement, Refactoring

#76 Sanitize request.body properties from forms' input of front-end or JSON sent to API
  back/app/middlewares/sanitizer.js
  back/app/router.js
  back/package.json
  back/yarn.lock
Labels: enhancement
